[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
solc_version = "0.8.23"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Gas limit for tests
gas_limit = 9223372036854775807

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
]

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"

[etherscan]
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
